services:
  - type: web
    name: taskmanager-backend
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: taskmanager-db
    region: singapore
